; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

define <8 x double> @test_simplify_unstrided_load(ptr %src) {
; CHECK-LABEL: define <8 x double> @test_simplify_unstrided_load(
; CHECK-SAME: ptr [[SRC:%.*]]) {
; CHECK-NEXT:    [[L:%.*]] = load <8 x double>, ptr [[SRC]], align 64
; CHECK-NEXT:    ret <8 x double> [[L]]
;
  %l = call <8 x double> @llvm.matrix.column.major.load.v8f64.i64(ptr %src, i64 4, i1 false, i32 4, i32 2);
  ret <8 x double> %l
}

define <8 x double> @test_no_simplify_strided_load(ptr %src) {
; CHECK-LABEL: define <8 x double> @test_no_simplify_strided_load(
; CHECK-SAME: ptr [[SRC:%.*]]) {
; CHECK-NEXT:    [[L:%.*]] = call <8 x double> @llvm.matrix.column.major.load.v8f64.i64(ptr [[SRC]], i64 8, i1 false, i32 4, i32 2)
; CHECK-NEXT:    ret <8 x double> [[L]]
;
  %l = call <8 x double> @llvm.matrix.column.major.load.v8f64.i64(ptr %src, i64 8, i1 false, i32 4, i32 2);
  ret <8 x double> %l
}

define <8 x double> @test_no_simplify_dynamically_strided_load(ptr %src, i64 %stride) {
; CHECK-LABEL: define <8 x double> @test_no_simplify_dynamically_strided_load(
; CHECK-SAME: ptr [[SRC:%.*]], i64 [[STRIDE:%.*]]) {
; CHECK-NEXT:    [[L:%.*]] = call <8 x double> @llvm.matrix.column.major.load.v8f64.i64(ptr [[SRC]], i64 [[STRIDE]], i1 false, i32 4, i32 2)
; CHECK-NEXT:    ret <8 x double> [[L]]
;
  %l = call <8 x double> @llvm.matrix.column.major.load.v8f64.i64(ptr %src, i64 %stride, i1 false, i32 4, i32 2);
  ret <8 x double> %l
}

define void @test_simplify_unstrided_store(ptr %dst) {
; CHECK-LABEL: define void @test_simplify_unstrided_store(
; CHECK-SAME: ptr [[DST:%.*]]) {
; CHECK-NEXT:    store <8 x double> zeroinitializer, ptr [[DST]], align 64
; CHECK-NEXT:    ret void
;
  call void @llvm.matrix.column.major.store.v8f64.i64(<8 x double> zeroinitializer, ptr %dst, i64 4, i1 false, i32 4, i32 2)
  ret void
}

define void @test_no_simplify_strided_store(ptr %dst) {
; CHECK-LABEL: define void @test_no_simplify_strided_store(
; CHECK-SAME: ptr [[DST:%.*]]) {
; CHECK-NEXT:    call void @llvm.matrix.column.major.store.v8f64.i64(<8 x double> zeroinitializer, ptr [[DST]], i64 8, i1 false, i32 4, i32 2)
; CHECK-NEXT:    ret void
;
  call void @llvm.matrix.column.major.store.v8f64.i64(<8 x double> zeroinitializer, ptr %dst, i64 8, i1 false, i32 4, i32 2)
  ret void
}

define void @test_no_simplify_dynamically_strided_store(ptr %dst, i64 %stride) {
; CHECK-LABEL: define void @test_no_simplify_dynamically_strided_store(
; CHECK-SAME: ptr [[DST:%.*]], i64 [[STRIDE:%.*]]) {
; CHECK-NEXT:    call void @llvm.matrix.column.major.store.v8f64.i64(<8 x double> zeroinitializer, ptr [[DST]], i64 [[STRIDE]], i1 false, i32 4, i32 2)
; CHECK-NEXT:    ret void
;
  call void @llvm.matrix.column.major.store.v8f64.i64(<8 x double> zeroinitializer, ptr %dst, i64 %stride, i1 false, i32 4, i32 2)
  ret void
}

declare <8 x double> @llvm.matrix.column.major.load.v8f64.i64(ptr, i64, i1, i32, i32)
declare void @llvm.matrix.column.major.store.v8f64.i64(<8 x double>, ptr, i64, i1, i32, i32)
